/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

/**********************************************************************
 * 当前登录用户
 */
var loginUser, imageSizeMap, orderAutoLoadTime, subCommissionBase, resourceUrl, recruitBusinessTreeNodes, /*makeOrderTreeNodes,*/customerServiceTreeNodes, nomalManagerTreeNodes, systemManagerTreeNodes;
var /*anXinBuyManagerTreeNodes,guaranteeTreeNodes,*/receivingTreeNodes;

(function () {
    var queryCurrentInfo = function () {
        //Ajax请求当前登录用户信息
        Ext.Ajax.request({
            url: './main/currentLoginUserInfo.action',
            async: false,
            success: function (response, opts) {
                var result = Ext.decode(response.responseText);
                //设置当前登录用户信息
                loginUser = result.currentUser;
            }
        });
    };
    queryCurrentInfo();
    setInterval(function () {
        queryCurrentInfo();
    }, Common.config.UPDATE_INFO_INTERVAL * 1000);

    //普通管理员菜单项
    nomalManagerTreeNodes = [

        {
            text: '用户管理', expanded: true,
            children: [{
                text: '客服信息管理', leaf: true, id: 'userManager'
            }, {
                text: '修改密码', leaf: true, id: 'modifyPassword'
            }],
        }, {
            text: '7bao账号', expanded: true,
            children: [{
                text: '7bao账号管理', leaf: true, id: 'sevenBaoAccoutManager'
            }]
        }, {
            text: '收货配置', expanded: true,
            children: [{
                text: '收货系统配置', leaf: true, id: 'zbaoShManager'
            }, {
                text: '资金明细', leaf: true, id: 'zbaoFundDetailManager'
            }, {
                text: '充值明细', leaf: true, id: 'zbaoPayOrderManager'
            }, {
                text: '提现明细', leaf: true, id: 'zbaoWithdrawalsManager'
            }, {
                text: '采购转账明细', leaf: true, id: 'zbaoTransferManager'
            }]
        }, {
            text: '银行信息管理', expanded: true,
            children: [{
                text: '银行信息管理', leaf: true, id: 'zbaoBankManager'
            }]
        }, {
            text: '服务费配置管理', expanded: true,
            children: [{
                text: '服务费配置表', leaf: true, id: 'zbaoAmountConfigManager'
            }]
        },
        {
            text: '资金平衡表', expanded: true,
            children: [{
                text: '资金平衡表', leaf: true, id: 'FundStatisticsManager'
            }]
        }
    ];

    receivingTreeNodes = [];

    //系统管理员菜单项
    systemManagerTreeNodes = Ext.Array.merge(nomalManagerTreeNodes, receivingTreeNodes);
})();

Ext.define('SystemUtil', {
    singleton: true,
    getImageUrl: function (url, type) {
        if (Ext.isEmpty(url)) {
            return url;
        }
        var strs = url.split('.jpg');
        if (strs.length == 2) {
            return Common.config.RESOURCE_URL + strs[0] + imageSizeMap[type] + '.jpg';
        }
        strs = url.split('.png');
        if (strs.length == 2) {
            return Common.config.RESOURCE_URL + strs[0] + imageSizeMap[type] + '.png';
        }
        strs = url.split('.gif');
        if (strs.length == 2) {
            return Common.config.RESOURCE_URL + strs[0] + imageSizeMap[type] + '.gif';
        }
        strs = url.split('.bmp');
        if (strs.length == 2) {
            return Common.config.RESOURCE_URL + strs[0] + imageSizeMap[type] + '.bmp';
        }
        return url;
    },
    getOrderAutoLoadTime: function () {
        return orderAutoLoadTime;
    },
    getSubCommissionBase: function () {
        return subCommissionBase;
    }
});

Ext.define('CurrentUser', {
    singleton: true,
    /**
     * 当前登录用户对象
     */
    getCurrentUser: function () {
        if (!Ext.isEmpty(loginUser)) {
            return loginUser;
        }
    },
    /**
     * 当前登录用户的用户名
     */
    getRealName: function () {
        if (!Ext.isEmpty(loginUser)) {
            return CurrentUser.getCurrentUser().realName;
        }
    },
    /**
     * 当前登录用户的用户名
     */
    getLoginAccount: function () {
        if (!Ext.isEmpty(loginUser)) {
            return CurrentUser.getCurrentUser().loginAccount;
        }
    },
    /**
     * 当前登录用户类型编码
     */
    getUserTypeCode: function () {
        if (!Ext.isEmpty(loginUser)) {
            return CurrentUser.getCurrentUser().userType;
        }
    },
    /**
     * 当前登录用户类型名称
     */
    getUserTypeName: function () {
        if (!Ext.isEmpty(loginUser)) {
            return DataDictionary.rendererSubmitToDisplay(CurrentUser.getUserTypeCode());
        }
    },
    /**
     * 当前登录用户菜单
     */
    getUserMenus: function () {
        if (!Ext.isEmpty(loginUser)) {
            return userMenus = systemManagerTreeNodes;
            ;
        }
    }
});

Ext.application({
    models: [
        'UserModel',
        'sevenBaoAccoutModel',
    ],
    stores: [
        'MenuTreeStore',
        'sevenBaoAccoutStore',
        'UserStore',
    ],
    views: [
        'Viewport',
    ],
    autoCreateViewport: true,
    name: 'MyApp'
});
Ext.QuickTips.init();